/**
 * SSE Stream Engine for CodexBridge (OpenCodex V2)
 * Converts OpenAI Chat Completions SSE deltas into 4 core Responses stream categories:
 * 1. output_text.delta
 * 2. function_call_arguments.delta
 * 3. lifecycle (created, added, done, completed)
 *
 * Third-party reasoning is deliberately kept internal.  The local `rs_*`
 * identifiers generated by this gateway are not persisted by the official
 * Responses service, so exposing them to Codex Desktop poisons the thread
 * when the user later switches back to a native GPT model.
 */

import { randomBytes } from "crypto";
import { NATIVE_IMAGE_TOOL_NAME } from "../services/native_image_bridge.js";
import {
  nativeComputerUseMcpDescriptor,
  normalizeNativeComputerUseToolArguments,
} from "../services/computer_use_native.js";

export class ThinkTagFilter {
  private isThinking = false;
  private buffer = "";

  public filter(chunk: string): { text: string; reasoning: string } {
    this.buffer += chunk;
    let text = "";
    let reasoning = "";

    while (this.buffer.length > 0) {
      if (!this.isThinking) {
        const thinkIdx = this.buffer.indexOf("<think>");
        if (thinkIdx !== -1) {
          text += this.buffer.slice(0, thinkIdx);
          this.isThinking = true;
          this.buffer = this.buffer.slice(thinkIdx + 7);
        } else {
          let partial = false;
          for (let i = 1; i < 7; i++) {
            if (this.buffer.endsWith("<think>".slice(0, i))) {
              text += this.buffer.slice(0, -i);
              this.buffer = this.buffer.slice(-i);
              partial = true;
              break;
            }
          }
          if (!partial) {
            text += this.buffer;
            this.buffer = "";
          } else {
            break;
          }
        }
      } else {
        const endThinkIdx = this.buffer.indexOf("</think>");
        if (endThinkIdx !== -1) {
          reasoning += this.buffer.slice(0, endThinkIdx);
          this.isThinking = false;
          this.buffer = this.buffer.slice(endThinkIdx + 8);
        } else {
          let partial = false;
          for (let i = 1; i < 8; i++) {
            if (this.buffer.endsWith("</think>".slice(0, i))) {
              reasoning += this.buffer.slice(0, -i);
              this.buffer = this.buffer.slice(-i);
              partial = true;
              break;
            }
          }
          if (!partial) {
            reasoning += this.buffer;
            this.buffer = "";
          } else {
            break;
          }
        }
      }
    }

    return { text, reasoning };
  }

  public flush(): { text: string; reasoning: string } {
    const remaining = this.buffer;
    const wasThinking = this.isThinking;
    this.buffer = "";
    this.isThinking = false;
    return wasThinking ? { text: "", reasoning: remaining } : { text: remaining, reasoning: "" };
  }
}

function generateHexId(prefix: string, length = 16): string {
  return `${prefix}_${randomBytes(Math.ceil(length / 2)).toString("hex").slice(0, length)}`;
}

/**
 * The desktop client owns permission prompts.  When a provider emits a shell
 * call that writes to a protected user folder, add the native escalation
 * fields at the protocol boundary instead of teaching the model to ask for
 * them in a prompt.
 */
export function normalizeToolArguments(name: string, rawArguments: string): string {
  if (name !== "exec_command" || !rawArguments) return rawArguments;

  let parsed: any;
  try {
    parsed = JSON.parse(rawArguments);
  } catch {
    return rawArguments;
  }
  if (!parsed || typeof parsed !== "object" || typeof parsed.cmd !== "string") return rawArguments;
  if (parsed.sandbox_permissions) return rawArguments;

  const command = parsed.cmd;
  const touchesProtectedFolder = /(?:~|\/Users\/[^\s"'`]+)\/(?:Desktop|Downloads|Pictures|Movies|Music)(?:\/|[\s"'`]|$)/i.test(command);
  const writesFiles = /(?:^|[;&|]\s*)(?:cat|cp|mv|ditto|tee|touch|mkdir|rm|rmdir|install|python(?:3)?|node|osascript)\b/i.test(command)
    || /(?:>>?|<<)\s*(?:~|\/Users\/)/.test(command);
  if (!touchesProtectedFolder || !writesFiles) return rawArguments;

  return JSON.stringify({
    ...parsed,
    sandbox_permissions: "require_escalated",
    justification: parsed.justification || "Access a protected local folder for the user's requested operation",
  });
}

function extractXmlAndBashToolCalls(text: string): { cleanText: string; calls: any[] } {
  let cleanText = text;
  const calls: any[] = [];

  // 1. Check for Grok-style inline text tool calls only if Grok token artifacts are present
  if (text.includes("montee") || text.includes("mont_call") || text.includes("mont_")) {
    const grokInlineRegex = /(?:montee\d+a|mont_?call_?)(exec_command|view_file|list_dir|write_stdin)([\s\S]*?)(?=(?:\n\n|\n[A-Z\u4e00-\u9fa5]|$))/gi;
    let grokMatch: RegExpExecArray | null;
    while ((grokMatch = grokInlineRegex.exec(text)) !== null) {
      const fnName = grokMatch[1];
      const rawParamText = grokMatch[2].trim();
      let cmd = "";

      const cmdMatch = rawParamText.match(/\.command\.(.*?)(?:\.workdir|\.description|\.duration|\.with_|\.justification|$)/s);
      if (cmdMatch) {
        cmd = cmdMatch[1].trim();
      } else {
        cmd = rawParamText;
      }

      calls.push({
        index: calls.length,
        id: `call_grok_${Date.now()}_${calls.length}`,
        type: "function",
        function: { name: fnName, arguments: JSON.stringify({ cmd: cmd || 'echo "hello from codex"' }) }
      });
    }
  }

  const bashRegex = /<bash>([\s\S]*?)<\/bash>/gi;
  let match: RegExpExecArray | null;
  while ((match = bashRegex.exec(text)) !== null) {
    const cmd = match[1].trim();
    calls.push({
      index: calls.length,
      id: `call_bash_${Date.now()}_${calls.length}`,
      type: "function",
      function: { name: "exec_command", arguments: JSON.stringify({ cmd }) }
    });
  }

  const toolCallRegex = /<tool_call(?:\s+name=["']([^"']+)["'])?\s*>([\s\S]*?)<\/tool_call>/gi;
  while ((match = toolCallRegex.exec(text)) !== null) {
    let fnName = match[1] || "";
    let rawArgs = match[2].trim();

    // Strip markdown json codeblock wrapping if present
    rawArgs = rawArgs.replace(/^```(?:json)?/i, "").replace(/```$/, "").trim();

    if (!fnName) {
      try {
        const parsed = JSON.parse(rawArgs);
        if (parsed.name) fnName = parsed.name;
        if (parsed.arguments) rawArgs = typeof parsed.arguments === "string" ? parsed.arguments : JSON.stringify(parsed.arguments);
        else if (parsed.parameters) rawArgs = typeof parsed.parameters === "string" ? parsed.parameters : JSON.stringify(parsed.parameters);
      } catch {}
    }

    if (!fnName) fnName = "exec_command";
    if (fnName === "run_shell" || fnName === "shell" || fnName === "bash" || fnName === "terminal") {
      fnName = "exec_command";
      try {
        const parsed = JSON.parse(rawArgs);
        if (parsed.command) rawArgs = JSON.stringify({ cmd: parsed.command });
      } catch {}
    }

    calls.push({
      index: calls.length,
      id: `call_xml_${Date.now()}_${calls.length}`,
      type: "function",
      function: { name: fnName, arguments: rawArgs }
    });
  }

  if (calls.length > 0) {
    if (text.includes("montee") || text.includes("mont_call")) {
      cleanText = cleanText.replace(/(?:montee\d+a|mont_?call_?)(exec_command|view_file|list_dir|write_stdin)[\s\S]*?(?=(?:\n\n|\n[A-Z\u4e00-\u9fa5]|$))/gi, "");
    }
    cleanText = cleanText
      .replace(/<bash>[\s\S]*?<\/bash>/gi, "")
      .replace(/<tool_calls>[\s\S]*?<\/tool_calls>/gi, "")
      .replace(/<tool_call(?:\s+name=["'][^"']+["'])?\s*>[\s\S]*?<\/tool_call>/gi, "")
      .replace(/saturatingtool_call:[^\n]*/gi, "")
      .trim();
  }

  return { cleanText, calls };
}

interface ToolCallState {
  id: string;
  call_id: string;
  name: string;
  namespace?: string;
  thought_signature?: string;
  arguments: string;
  output_index: number;
  added: boolean;
  closed: boolean;
  deferArguments?: boolean;
}

export interface InternalToolCall {
  id: string;
  call_id: string;
  name: string;
  arguments: string;
  thought_signature?: string;
}

interface ReasoningState {
  id: string;
  output_index: number;
  text: string;
  closed: boolean;
}

interface ImageGenerationState {
  id: string;
  output_index: number;
  result: string;
  revised_prompt?: string;
  closed: boolean;
}

function normalizeResponseUsage(raw: any): Record<string, any> | undefined {
  if (!raw || typeof raw !== "object") return undefined;
  const rawInput = Number(raw.input_tokens ?? raw.prompt_tokens);
  const rawOutput = Number(raw.output_tokens ?? raw.completion_tokens);
  const input = Number.isFinite(rawInput) ? rawInput : 0;
  const output = Number.isFinite(rawOutput) ? rawOutput : 0;
  const rawTotal = Number(raw.total_tokens);
  const total = Number.isFinite(rawTotal) ? rawTotal : input + output;
  if (![rawInput, rawOutput, rawTotal].some((value) => Number.isFinite(value))) return undefined;

  const usage: Record<string, any> = {};
  if (Number.isFinite(input)) usage.input_tokens = input;
  if (Number.isFinite(output)) usage.output_tokens = output;
  if (Number.isFinite(total)) usage.total_tokens = total;
  const rawDetails = raw.input_tokens_details && typeof raw.input_tokens_details === "object"
    ? raw.input_tokens_details
    : raw.prompt_tokens_details && typeof raw.prompt_tokens_details === "object"
      ? raw.prompt_tokens_details
      : {};
  const rawCached = Number(raw.cached_tokens ?? raw.cached_input_tokens ?? rawDetails.cached_tokens);
  // Codex Desktop parses the Responses usage shape strictly. Several
  // OpenAI-compatible providers emit input_tokens_details without the
  // required cached_tokens member; default that optional metric to zero at
  // the compatibility boundary instead of making the whole stream fail.
  usage.input_tokens_details = {
    ...rawDetails,
    cached_tokens: Number.isFinite(rawCached) ? rawCached : 0,
  };
  return usage;
}

export class ResponsesStreamEngine {
  private responseId: string;
  private model: string;
  private nextOutputIndex = 0;

  private messageItemId: string;
  private messageIndex: number | null = null;
  private messageText = "";
  private messageOpened = false;
  private messageClosed = false;

  private toolCalls: Record<number, ToolCallState> = {};
  private internalToolCalls: Record<number, ToolCallState> = {};
  private internalImageToolCalls: Record<number, ToolCallState> = {};
  private imageGenerations: ImageGenerationState[] = [];
  private reasoningState: ReasoningState | null = null;
  // Keep provider-native thinking private to the gateway. Some Chat
  // providers require the exact reasoning_content to be echoed on the next
  // request that follows a tool call, while Codex Desktop must not receive
  // or persist that provider-private chain of thought.
  private providerReasoningContent = "";

  private thinkFilter = new ThinkTagFilter();
  private turnId?: string;
  private forceCommentary = false;
  private internalToolNames: Set<string>;
  private usage?: Record<string, any>;

  constructor(model: string, turnId?: string, options?: { forceCommentary?: boolean; responseModel?: string; internalToolNames?: string[] }) {
    this.model = options?.responseModel || model;
    this.responseId = generateHexId("resp", 24);
    this.messageItemId = generateHexId("msg", 24);
    this.turnId = turnId;
    this.forceCommentary = options?.forceCommentary === true;
    this.internalToolNames = new Set((options?.internalToolNames || []).map((name) => String(name || "").trim().toLowerCase()).filter(Boolean));
  }

  public getResponseId(): string {
    return this.responseId;
  }

  public getMessageText(): string {
    return this.messageText;
  }

  public getReasoningContent(): string {
    return this.providerReasoningContent;
  }

  public getToolCallIds(): string[] {
    return Object.values(this.toolCalls)
      .map((state) => state.call_id)
      .filter((callId) => Boolean(callId));
  }

  /**
   * A few OpenAI-compatible gateways close a successful SSE body without a
   * final `[DONE]` or `finish_reason`. Let the HTTP boundary distinguish that
   * case from an empty/failed provider response without inventing assistant
   * content.
   */
  public hasOutput(): boolean {
    return Boolean(
      this.messageText.trim() ||
      Object.keys(this.toolCalls).length > 0 ||
      Object.keys(this.internalToolCalls).length > 0 ||
      this.imageGenerations.length > 0 ||
      this.reasoningState,
    );
  }

  /** Preserve provider usage for the Responses response consumed by Codex. */
  public observeProviderChunk(chunk: any): void {
    const usage = normalizeResponseUsage(chunk?.usage || chunk?.response?.usage);
    if (usage) this.usage = usage;
  }

  /** Internal gateway tool calls are deliberately never emitted as client tools. */
  public getInternalImageToolCalls(): Array<{ id: string; call_id: string; name: string; arguments: string }> {
    return Object.values(this.internalImageToolCalls).map((state) => ({
      id: state.id,
      call_id: state.call_id,
      name: state.name,
      arguments: state.arguments,
    }));
  }

  /**
   * Consume gateway-owned tool calls without exposing them to Codex Desktop.
   * The router executes these calls and continues the provider conversation
   * with the resulting function outputs.
   */
  public takeInternalToolCalls(): InternalToolCall[] {
    const calls = Object.values(this.internalToolCalls).map((state) => ({
      id: state.id,
      call_id: state.call_id,
      name: state.name,
      arguments: state.arguments,
      ...(state.thought_signature ? { thought_signature: state.thought_signature } : {}),
    }));
    this.internalToolCalls = {};
    return calls;
  }

  private wrap(writeSse: (payload: any) => Promise<void>) {
    return async (payload: any) => {
      if (payload && typeof payload === "object" && typeof payload.type === "string" && payload.type.startsWith("response.")) {
        payload = {
          ...payload,
          response_id: payload.response_id || this.responseId,
          ...(this.turnId ? { turn_id: this.turnId } : {}),
        };
      }
      await writeSse(payload);
    };
  }

  public async start(writeSse: (payload: any) => Promise<void>): Promise<void> {
    const emit = this.wrap(writeSse);
    await emit({
      type: "response.created",
      response: {
        id: this.responseId,
        object: "response",
        created_at: Math.floor(Date.now() / 1000),
        status: "in_progress",
        model: this.model,
        output: [],
      },
    });
    await emit({
      type: "response.in_progress",
      response: {
        id: this.responseId,
        object: "response",
        created_at: Math.floor(Date.now() / 1000),
        status: "in_progress",
        model: this.model,
        output: [],
      },
    });
  }

  private async openReasoning(writeSse: (payload: any) => Promise<void>): Promise<ReasoningState> {
    const emit = this.wrap(writeSse);
    const state: ReasoningState = {
      id: generateHexId("rs", 16),
      output_index: this.nextOutputIndex++,
      text: "",
      closed: false,
    };
    this.reasoningState = state;

    await emit({
      type: "response.output_item.added",
      output_index: state.output_index,
      item: {
        id: state.id,
        type: "reasoning",
        status: "in_progress",
        summary: [],
        content: [],
        encrypted_content: null,
      },
    });

    await emit({
      type: "response.content_part.added",
      item_id: state.id,
      output_index: state.output_index,
      content_index: 0,
      part: { type: "reasoning_text", text: "" },
    });

    return state;
  }

  private async emitReasoningDelta(writeSse: (payload: any) => Promise<void>, text: string): Promise<void> {
    // Never expose third-party chain-of-thought as a Responses reasoning item.
    // In particular, do not allocate an `rs_*` id here: Codex Desktop may
    // persist that item and replay it against chatgpt.com, where it does not
    // exist because the gateway cannot store it upstream.
    void writeSse;
    if (text) this.providerReasoningContent += text;
  }

  private async closeReasoning(writeSse: (payload: any) => Promise<void>): Promise<void> {
    void writeSse;
  }

  private async openMessage(writeSse: (payload: any) => Promise<void>): Promise<void> {
    if (this.messageOpened) return;
    const emit = this.wrap(writeSse);
    this.messageIndex = this.nextOutputIndex++;
    this.messageOpened = true;

    const phase = this.forceCommentary || Object.keys(this.toolCalls).length > 0
      ? "commentary"
      : "final_answer";
    await emit({
      type: "response.output_item.added",
      output_index: this.messageIndex,
      item: {
        id: this.messageItemId,
        type: "message",
        status: "in_progress",
        role: "assistant",
        phase,
        content: [],
      },
    });

    await emit({
      type: "response.content_part.added",
      item_id: this.messageItemId,
      output_index: this.messageIndex,
      content_index: 0,
      part: { type: "output_text", text: "", annotations: [] },
    });
  }

  private async emitTextDelta(writeSse: (payload: any) => Promise<void>, text: string): Promise<void> {
    if (!text) return;
    if (!this.messageOpened) {
      await this.openMessage(writeSse);
    }
    const emit = this.wrap(writeSse);
    this.messageText += text;
    await emit({
      type: "response.output_text.delta",
      item_id: this.messageItemId,
      output_index: this.messageIndex!,
      content_index: 0,
      delta: text,
    });

    // Real-time broadcast to active voice companion clients for TTS narration
    try {
      const msg = JSON.stringify({ type: "model_chunk", text });
      // @ts-ignore
      if (global.activeWsClients) {
        // @ts-ignore
        for (const client of global.activeWsClients) {
          if (client.readyState === 1 /* OPEN */) {
            client.send(msg);
          }
        }
      }
    } catch {}
  }

  private async emitToolDelta(writeSse: (payload: any) => Promise<void>, call: any): Promise<void> {
    const index = Number(call.index || 0);
    const fn = call.function || {};
    const isInternalImageCall = fn.name === NATIVE_IMAGE_TOOL_NAME || Boolean(this.internalImageToolCalls[index]);
    const isInternalGatewayCall = this.internalToolNames.has(String(fn.name || "").trim().toLowerCase()) || Boolean(this.internalToolCalls[index]);
    const mcpDescriptor = nativeComputerUseMcpDescriptor(fn.name);
    const nativeIdentity = mcpDescriptor
      ? { name: mcpDescriptor.toolName, namespace: `mcp__${mcpDescriptor.serverLabel}` }
      : undefined;
    const toolStore = isInternalImageCall
      ? this.internalImageToolCalls
      : isInternalGatewayCall
        ? this.internalToolCalls
        : this.toolCalls;
    let state = toolStore[index];

    if (!state) {
      // Responses separates the persisted function-call item id (`fc_*`)
      // from the provider/tool correlation id (`call_*`).  Upstream Chat
      // Completions providers commonly return call_* for both, but forwarding
      // that value as the Responses item id makes native continuation reject
      // the saved input with invalid_id_prefix.
      const callId = call.call_id || call.id || `call_${index}`;
      const itemId = typeof call.id === "string" && /^fc_[A-Za-z0-9_-]+$/.test(call.id)
          ? call.id
          : generateHexId("fc", 24);
      state = {
        id: itemId,
        call_id: callId,
        name: nativeIdentity?.name || fn.name || "",
        ...(nativeIdentity?.namespace ? { namespace: nativeIdentity.namespace } : {}),
        ...((call.thought_signature || call.thoughtSignature || call.signature)
          ? { thought_signature: String(call.thought_signature || call.thoughtSignature || call.signature) }
          : {}),
        arguments: "",
        output_index: isInternalImageCall ? -1 : this.nextOutputIndex++,
        added: isInternalImageCall,
        closed: false,
        deferArguments: !isInternalImageCall && (
          isInternalGatewayCall ||
          (fn.name || "") === "exec_command" ||
          Boolean(nativeIdentity)
        ),
      };
      toolStore[index] = state;
    }

    if (nativeIdentity) {
      state.name = nativeIdentity.name;
      state.namespace = nativeIdentity.namespace;
      state.deferArguments = true;
    } else if (fn.name && !state.name) {
      state.name = fn.name;
    }
    if (call.thought_signature || call.thoughtSignature || call.signature) {
      state.thought_signature = String(call.thought_signature || call.thoughtSignature || call.signature);
    }

    if (isInternalImageCall || isInternalGatewayCall) {
      if (fn.arguments) state.arguments += fn.arguments;
      return;
    }

    const emit = this.wrap(writeSse);
    if (!state.added) {
      state.added = true;
      await emit({
        type: "response.output_item.added",
        output_index: state.output_index,
        item: {
          id: state.id,
          type: "function_call",
          status: "in_progress",
          call_id: state.call_id,
          name: state.name,
          arguments: "",
          ...(state.namespace ? { namespace: state.namespace } : {}),
        },
      });
    }

    if (fn.arguments) {
      state.arguments += fn.arguments;
      if (!state.deferArguments) {
        await emit({
          type: "response.function_call_arguments.delta",
          item_id: state.id,
          output_index: state.output_index,
          delta: fn.arguments,
        });
      }
    }
  }

  /**
   * Add a completed image result as a native Responses image_generation_call
   * output item. The base64 result is emitted only after the bridge succeeds.
   */
  public async emitImageGeneration(
    writeSse: (payload: any) => Promise<void>,
    image: { result: string; revised_prompt?: string; partial_images?: string[] },
  ): Promise<void> {
    if (!image.result) return;
    const emit = this.wrap(writeSse);
    const state: ImageGenerationState = {
      id: generateHexId("ig", 24),
      output_index: this.nextOutputIndex++,
      result: image.result,
      ...(image.revised_prompt ? { revised_prompt: image.revised_prompt } : {}),
      closed: false,
    };
    this.imageGenerations.push(state);

    await emit({
      type: "response.output_item.added",
      output_index: state.output_index,
      item: {
        id: state.id,
        type: "image_generation_call",
        status: "in_progress",
        ...(state.revised_prompt ? { revised_prompt: state.revised_prompt } : {}),
      },
    });

    const partials = Array.isArray(image.partial_images) && image.partial_images.length > 0
      ? image.partial_images
      : [];
    for (let index = 0; index < partials.length; index += 1) {
      const partial = partials[index];
      if (!partial) continue;
      await emit({
        type: "response.image_generation_call.partial_image",
        item_id: state.id,
        output_index: state.output_index,
        partial_image_index: index,
        partial_image_b64: partial,
      });
    }
  }

  public async processChatChunk(writeSse: (payload: any) => Promise<void>, chunk: any): Promise<void> {
    this.observeProviderChunk(chunk);
    const emit = this.wrap(writeSse);
    // OpenAI-compatible providers may send an informational chunk with an
    // empty `choices` array before the first token or at stream completion.
    // Treat it as a no-op instead of dereferencing an absent choice and
    // aborting the whole Live/tool continuation.
    const choices = Array.isArray(chunk?.choices) ? chunk.choices : [];
    const choice = choices[0] && typeof choices[0] === "object" ? choices[0] : {};
    const delta = choice.delta && typeof choice.delta === "object" ? choice.delta : {};

    const reasoning = delta.reasoning_content || delta.reasoning || choice.message?.reasoning_content;
    if (reasoning) {
      await this.emitReasoningDelta(emit, reasoning);
    }

    const rawContent = delta.content ?? delta.text ?? choice.text ?? choice.message?.content;
    const content = typeof rawContent === "string" ? rawContent : "";

    if (content) {
      const { text: filteredText, reasoning: thinkReasoning } = this.thinkFilter.filter(content);
      if (thinkReasoning) {
        await this.emitReasoningDelta(emit, thinkReasoning);
      }
      if (filteredText) {
        const { cleanText, calls: parsedXmlCalls } = extractXmlAndBashToolCalls(filteredText);
        if (cleanText) {
          await this.closeReasoning(emit);
          await this.emitTextDelta(emit, cleanText);
        }
        for (const call of parsedXmlCalls) {
          await this.closeReasoning(emit);
          await this.emitToolDelta(emit, call);
        }
      }
    }

    const toolCalls = Array.isArray(delta.tool_calls) ? delta.tool_calls : [];
    for (const call of toolCalls) {
      await this.closeReasoning(emit);
      await this.emitToolDelta(emit, call);
    }
  }

  public async finish(writeSse: (payload: any) => Promise<void>): Promise<void> {
    const emit = this.wrap(writeSse);

    const { text: flushedText, reasoning: flushedReasoning } = this.thinkFilter.flush();
    if (flushedReasoning) {
      await this.emitReasoningDelta(emit, flushedReasoning);
    }
    await this.closeReasoning(emit);

    const hasTools = Object.keys(this.toolCalls).length > 0;
    const messagePhase = this.forceCommentary || hasTools ? "commentary" : "final_answer";
    const hasImages = this.imageGenerations.length > 0;
    if (flushedText && !this.messageClosed) {
      await this.emitTextDelta(emit, flushedText);
    }

    if (!hasTools && !hasImages && (!this.messageText || this.messageText.trim().length === 0)) {
      if (!this.messageOpened) {
        await this.openMessage(emit);
      }
    }

    // Close output items in the same order in which they were announced.
    // Starting with an empty message and closing it before a tool call made
    // the desktop renderer defer the visible turn until the next response.
    const outputIndexes: number[] = [];
    if (this.messageOpened && !this.messageClosed) outputIndexes.push(this.messageIndex!);
    for (const state of Object.values(this.toolCalls)) {
      if (!state.closed) outputIndexes.push(state.output_index);
    }
    for (const state of this.imageGenerations) {
      if (!state.closed) outputIndexes.push(state.output_index);
    }
    outputIndexes.sort((a, b) => a - b);

    for (const outputIndex of outputIndexes) {
      if (this.messageOpened && !this.messageClosed && outputIndex === this.messageIndex) {
        this.messageClosed = true;
        await emit({
          type: "response.output_text.done",
          item_id: this.messageItemId,
          output_index: this.messageIndex!,
          content_index: 0,
          text: this.messageText,
        });
        await emit({
          type: "response.content_part.done",
          item_id: this.messageItemId,
          output_index: this.messageIndex!,
          content_index: 0,
          part: { type: "output_text", text: this.messageText, annotations: [] },
        });
        await emit({
          type: "response.output_item.done",
          output_index: this.messageIndex!,
          item: {
            id: this.messageItemId,
            type: "message",
            status: "completed",
            role: "assistant",
            phase: messagePhase,
            content: [{ type: "output_text", text: this.messageText, annotations: [] }],
          },
        });
        continue;
      }

      const state = Object.values(this.toolCalls).find((candidate) => candidate.output_index === outputIndex);
      if (state && !state.closed) {
        state.closed = true;
        const normalizedArguments = state.namespace === "mcp__node_repl"
          ? normalizeNativeComputerUseToolArguments(state.arguments)
          : normalizeToolArguments(state.name, state.arguments);
        if (state.deferArguments && normalizedArguments) {
          await emit({
            type: "response.function_call_arguments.delta",
            item_id: state.id,
            output_index: state.output_index,
            delta: normalizedArguments,
          });
        }
        state.arguments = normalizedArguments;
        await emit({
          type: "response.function_call_arguments.done",
          item_id: state.id,
          output_index: state.output_index,
          arguments: state.arguments,
        });
        await emit({
          type: "response.output_item.done",
          output_index: state.output_index,
          item: {
            id: state.id,
            type: "function_call",
            status: "completed",
            call_id: state.call_id,
            name: state.name,
            arguments: state.arguments,
            ...(state.namespace ? { namespace: state.namespace } : {}),
            ...(state.thought_signature ? { thought_signature: state.thought_signature, thoughtSignature: state.thought_signature } : {}),
          },
        });
        continue;
      }

      const image = this.imageGenerations.find((candidate) => candidate.output_index === outputIndex);
      if (!image || image.closed) continue;
      image.closed = true;
      await emit({
        type: "response.output_item.done",
        output_index: image.output_index,
        item: {
          id: image.id,
          type: "image_generation_call",
          status: "completed",
          ...(image.revised_prompt ? { revised_prompt: image.revised_prompt } : {}),
          result: image.result,
        },
      });
    }

    const now = Math.floor(Date.now() / 1000);
    const output: any[] = [];
    if (this.messageOpened) {
      output.push({
        id: this.messageItemId,
        type: "message",
        status: "completed",
        role: "assistant",
        phase: messagePhase,
        content: [{ type: "output_text", text: this.messageText, annotations: [] }],
      });
    }
    for (const state of Object.values(this.toolCalls)) {
      output.push({
        id: state.id,
        type: "function_call",
        status: "completed",
        call_id: state.call_id,
        name: state.name,
        arguments: state.arguments,
        ...(state.namespace ? { namespace: state.namespace } : {}),
      });
    }
    for (const image of this.imageGenerations) {
      output.push({
        id: image.id,
        type: "image_generation_call",
        status: "completed",
        ...(image.revised_prompt ? { revised_prompt: image.revised_prompt } : {}),
        result: image.result,
      });
    }
    const completedResponse = {
      id: this.responseId,
      object: "response",
      created_at: now,
      completed_at: now,
      status: "completed",
      model: this.model,
      output,
      ...(this.usage ? { usage: this.usage } : {}),
    };
    await emit({
      type: "response.completed",
      response: completedResponse,
    });

    await emit({
      type: "response.done",
      response: completedResponse,
    });

    // Real-time broadcast to active voice companion clients for TTS finalization
    try {
      const msg = JSON.stringify({ type: "model_done", text: "" });
      // @ts-ignore
      if (global.activeWsClients) {
        // @ts-ignore
        for (const client of global.activeWsClients) {
          if (client.readyState === 1) {
            client.send(msg);
          }
        }
      }
    } catch {}
  }
}
